INSERT INTO user (name,surname,email,phone_number) VALUES ("Abra","Tillman","cubilia@consectetueradipiscingelit.ca","677371967");
INSERT INTO user (name,surname,email,phone_number) VALUES ("Beatrice","Velasquez","eget.varius@elitpellentesquea.org","400291792");
INSERT INTO user (name,surname,email,phone_number) VALUES ("Herrod","Martinez","neque.vitae.semper@vulputateullamcorper.co.uk","986649054");
INSERT INTO user (name,surname,email,phone_number) VALUES ("Priscilla","Brock","nec.euismod.in@inlobortis.ca","231349382");
INSERT INTO user (name,surname,email,phone_number) VALUES ("Minerva","Yang","Vivamus.molestie.dapibus@elitpharetra.ca","224884720");
INSERT INTO user (name,surname,email,phone_number) VALUES ("Declan","Hendricks","sollicitudin.adipiscing@euodiotristique.org","483509721");
INSERT INTO user (name,surname,email,phone_number) VALUES ("Mari","Ryan","Cras.vehicula.aliquet@sedconsequatauctor.ca","745604196");
INSERT INTO user (name,surname,email,phone_number) VALUES ("Jena","Hodge","ante@semmollisdui.ca","500564252");
INSERT INTO user (name,surname,email,phone_number) VALUES ("Christine","Valdez","a@estmaurisrhoncus.ca","017896929");
INSERT INTO user (name,surname,email,phone_number) VALUES ("Colt","Levy","cubilia.Curae.Donec@fringillaest.ca","768029478");

INSERT INTO item (name,description,category,item_status,notification_date,realization_date,weight,color,photo_url,id_user_finder,id_user_owner) VALUES ("Lost plates","ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac","OTHER","LOST","2017-09-07","2017-09-28","0.05","red","assets/items-img/1.jpg",2,2);
INSERT INTO item (name,description,category,item_status,notification_date,realization_date,weight,color,photo_url,id_user_finder,id_user_owner) VALUES ("ID in blue wallet","leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu,","DOCUMENTS","COMPLETED","2017-09-07","2017-09-23","21.3","indigo","assets/items-img/2.jpg",2,4);
INSERT INTO item (name,description,category,item_status,notification_date,realization_date,weight,color,photo_url,id_user_finder,id_user_owner) VALUES ("Samsung s7 gold","turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum.","PHONE","FOUND","2017-08-03","2017-09-21","22.5","gold","assets/items-img/3.jpg",4,4);
INSERT INTO item (name,description,category,item_status,notification_date,realization_date,weight,color,photo_url,id_user_finder,id_user_owner) VALUES ("Gold wirstclock with diamonds","pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis","CLOCK","FOUND","2017-09-01","2017-09-30","23.5","gold","assets/items-img/4.jpg",2,1);
INSERT INTO item (name,description,category,item_status,notification_date,realization_date,weight,color,photo_url,id_user_finder,id_user_owner) VALUES ("Leather wallet","non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed","WALLET","LOST","2017-09-04","2017-09-18","112.2","violet","assets/items-img/5.jpg",1,4);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_finder,id_user_owner) VALUES ("Rayban glasses","nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum","GLASSES","FOUND","2017-09-03","22.3","indigo","assets/items-img/6.jpg",1,3);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_finder,id_user_owner) VALUES ("Straight scarf","id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque","CLOTH","COMPLETED","2017-09-02","45.2","indigo","assets/items-img/7.jpg",2,1);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_owner) VALUES ("Red Sandal","vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit","CLOTH","FOUND","2017-09-06","0.08","red","assets/items-img/8.jpg",2);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_owner) VALUES ("Smartband xaoimi mi2","metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec","CLOCK","FOUND","2017-09-09","0.02","red","assets/items-img/10.jpg",3);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_owner) VALUES ("Yellow rayban limited","nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque","GLASSES","COMPLETED","2017-09-18","0.05","yellow","assets/items-img/9.jpg",4);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_finder) VALUES ("rolex silver","ornare, lectus ante dictum mi, ac mattis velit justo nec ante.","CLOCK","COMPLETED","2017-09-10","0.10","green","assets/items-img/10.jpg",2);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_finder) VALUES ("Nike backpack","sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel","BACKPACK","LOST","2017-09-14","0.03","blue","assets/items-img/11.jpg",4);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_finder) VALUES ("Glasess OKS","venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem","GLASSES","LOST","2017-09-04","0.03","violet","assets/items-img/12.jpg",2);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_finder) VALUES ("Red t-shirt","ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper","CLOTH","FOUND","2017-09-07","0.03","red","assets/items-img/13.jpg",1);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_finder) VALUES ("Wallet with pinguin","tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec","WALLET","LOST","2017-09-04","0.03","green","assets/items-img/14.jpg",4);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_finder) VALUES ("NoteBook","tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a","OTHER","COMPLETED","2017-09-08","0.08","yellow","assets/items-img/15.jpg",3);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_finder) VALUES ("Versace bag","consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue.","BAG","LOST","2017-09-21","0.08","orange","assets/items-img/16.jpg",3);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_finder) VALUES ("Id and driving licence","sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque","DOCUMENTS","COMPLETED","2017-09-10","0.10","orange","assets/items-img/17.jpg",1);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_finder) VALUES ("Orange glasses oks","lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc","GLASSES","LOST","2017-09-02","0.01","orange","assets/items-img/18.jpg",3);
INSERT INTO item (name,description,category,item_status,notification_date,weight,color,photo_url,id_user_finder) VALUES ("Driving licence","lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac,","DOCUMENTS","FOUND","2017-09-06","0.06","indigo","assets/items-img/19.jpg",2);

INSERT INTO item_wish_list (id_item,id_user) VALUES (6,3);
INSERT INTO item_wish_list (id_item,id_user) VALUES (3,4);
INSERT INTO item_wish_list (id_item,id_user) VALUES (20,4);
INSERT INTO item_wish_list (id_item,id_user) VALUES (7,6);
INSERT INTO item_wish_list (id_item,id_user) VALUES (3,1);
INSERT INTO item_wish_list (id_item,id_user) VALUES (2,1);
INSERT INTO item_wish_list (id_item,id_user) VALUES (11,2);
INSERT INTO item_wish_list (id_item,id_user) VALUES (12,6);
INSERT INTO item_wish_list (id_item,id_user) VALUES (5,5);
INSERT INTO item_wish_list (id_item,id_user) VALUES (2,7);
INSERT INTO item_wish_list (id_item,id_user) VALUES (11,8);
INSERT INTO item_wish_list (id_item,id_user) VALUES (3,9);
INSERT INTO item_wish_list (id_item,id_user) VALUES (12,4);
INSERT INTO item_wish_list (id_item,id_user) VALUES (10,3);
INSERT INTO item_wish_list (id_item,id_user) VALUES (18,8);
INSERT INTO item_wish_list (id_item,id_user) VALUES (15,5);
INSERT INTO item_wish_list (id_item,id_user) VALUES (13,2);
INSERT INTO item_wish_list (id_item,id_user) VALUES (9,10);
INSERT INTO item_wish_list (id_item,id_user) VALUES (7,7);
INSERT INTO item_wish_list (id_item,id_user) VALUES (5,10);
INSERT INTO item_wish_list (id_item,id_user) VALUES (13,9);
INSERT INTO item_wish_list (id_item,id_user) VALUES (20,7);
INSERT INTO item_wish_list (id_item,id_user) VALUES (8,2);